name: Daily X Posts

on:
  schedule:
    # Run at 9:00 AM UTC (adjust for your timezone)
    - cron: '40 5 * * *'
    # Run at 9:00 PM UTC (adjust for your timezone)  
    - cron: '5 16 * * *'
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  post-to-x:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Load post history (if exists)
      uses: actions/cache@v3
      with:
        path: post_history.json
        key: post-history-${{ github.sha }}
        restore-keys: |
          post-history-
          
    - name: Run X posting bot
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        POSTING_TOPIC: ${{ vars.POSTING_TOPIC || 'Artificial Intelligence' }}
        POSTING_TIME: ${{ github.event.schedule == '40 5 * * *' && '10:15' || '21:05' }}
      run: python posting_agent.py
      
    - name: Save post history
      uses: actions/cache/save@v3
      if: always()
      with:
        path: post_history.json
        key: post-history-${{ github.sha }}-${{ github.run_number }}
